language: scala
scala:
- 2.11.7
services:
- docker
script:
- sbt ++$TRAVIS_SCALA_VERSION compile test stage
env:
  global:
  - DOCKER_USERNAME=spamidiparthi
  - DOCKER_PASSWORD=default
deploy:
  skip_cleanup: true
  provider: script
  script: bash dockerpush
  on:
    branch: master
