language: scala
scala:
- 2.11.7
services:
- docker
script:
- sbt ++$TRAVIS_SCALA_VERSION compile test stage
env:
  global:
  - secure: TPR/8SFFhSsanXXLZY+9Ldirz69AEmi/ll/OjZmMr3SfNyQfVUdFEl92lpmewu1VX/J4ANOzqPwSnCwmgp5fPVAJLpd/JpmF8LGjUh3ZLPBjAsmLAevOs/ii2iTA/FahzvqwVba558a1ECEhsI5NgoDBvLcIIGwGcngl0Ll6Qazqts0DDwkmqo0iY0uQXD8iLoz1w/3LgBxDj825JQx2t0GTWUiHysez/ZneWS4CN0y5J0b7dCxyYxh2o90REuQGZgqhp27d1pAy1NBBd+g+cdGTe5aCFTkC7tIe0BpZjwLFtMHyIAAHOKDot2YaqhOenYqUbh5JtJQAXLp0J9SzXTOvJ79NEwf5k9nPEP/oEJ8+/CDebpoORMOf5DIvPB84xrkQeagGTbHAqw96YyPCJqe+ad6NZ7h0MErRe3Cl2r1ohamkXhB3xcsO4wDcjKxel8Ad0tJmW6PIU0NHopaj9vnR0i4DwNEyxrzxT6A4DhE1WrRbZYWgKHMK3RHj5p6b1KzIrn3ERAhCTFu2ZMMNEju4oLpl4bL3n9RAD9Un5uNfUFtMblCzt0qf9b/oefqXrFp74HOqs2Y2H7Yvor0YMkUxKcI2hKBvZm0XIB+xbFc5w6dpEKsCkCffVWjnxChFUXYLZKMI73UBxOcMQRb2+vXE30hp5CBJk9UjTy1jTNY=
  - secure: rWf5XAQ3kzJFgHETXoFGdtFdqr7qzZhXT/76vA4xZjaB9ZORgkNPmwR5G+IYyz9s0uoGfvvFaGTl83iTC/6PQJTBTww22ygB+ANavI72LhYyw0XAcBv/EPKvhUFoOWLdrfGx6isiNtx1m6Vh+cRkbVVsA+eL6z1e/Rmaiow42mdmHHMNl7austE8NJPRWbjb/XnqqJPzP2AzFQaZO5/gZMZhyMN0gCNGkCmDk4wQhofXvbp8tPUp0mi4X4mvCoykLGGHEjmvg/+vEj4GOaSn4tGzehMYD6Ikj+N0DJ2ze+3+zYSQxs72a29d9pew5gmXTmcC+SfmBy6PbSe84nXKnpmzmFoRrp5MnHZaOC89QgZhRqu5iZoHnkaWDGpOA+BfoyetEmiwQdJe+YWPy2+wT95r1A3v6Z8/4VJBlNK6RLj1Gx/iNTS/45Ibs20hNWZVW6kCJFMX4jcSTjcdhO/are9OC9qSM+bBYGjYoDatC8jWRt7bWhEMGJ3/qrSyp6+/8I1T43tqDzf+s0XrnRWskgXVsLaZ0Pug7qxQvVfIssn9ONAKJloNJSbN8dwfkFmeGLLs4APtqW3fLfsa2kHa/7ZR2QpELHFQ3HPTZFwkMI760PacYnNg9xBWjJYgbBxhYUDPLR5IxZmhHH+6Ohe3Xd8XeoFMZE9HpuKfNwAUa5k=
deploy:
  provider: script
  script: bash dockerpush
  on:
    branch: master
