language: scala
scala:
   - 2.12.7

services:
- docker

before_install:
- docker build -t spamidiparthi/cicd .
- docker run -d -p 127.0.0.1:80:4567 spamidiparthi/cicd /bin/sh -c "cd /root/cicd; bundle exec foreman start;"
- docker ps -a
- docker run spamidiparthi/cicd /bin/sh -c "cd /root/cicd; sbt test" #"bundle exec rake test"

script:
#- bundle exec rake test
- sbt test