#!/usr/bin/env bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t cicd .
docker images
docker tag cicd $DOCKER_USERNAME/cicd
docker push spamidiparthi/cicd
